name: ESLint

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run lint check
        run: npm run lint
      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check